---

- name: Download epel-release package
  get_url: url=${epel_release_url}/${epel_release_name} dest=/tmp/${epel_release_name} mode=0644
  environment: $proxy_env

- name: Install epel-release package
  command: yum install -y ${yum_flags} /tmp/${epel_release_name} creates=/etc/yum.repos.d/epel.repo
  environment: $proxy_env
