#!/bin/sh
export MSG_PORT=6163

source /etc/sysconfig/activemq_gip_provider

glite-info-service /etc/glite/info/service/glite-info-service-activemq-stomp.conf $SITENAME
glite-info-glue2-simple /etc/glite/info/service/glite-info-service-activemq-stomp.conf $SITENAME
